frontend:
  image: node:latest
  before_script:
    - cd frontend
    - npm ci --cache .npm --prefer-offline
  stage: build 
  script:
    - npm run build
  artifacts:
    paths:
      - frontend/dist
  only:
    refs:
      - master
    changes:
      - frontend/*