default:
  image: node:latest
  before_script:
    - npm ci --cache .npm --prefer-offline

frontend:
  stage: build 
  script:
    - npm run build
  artifacts:
    paths:
      - frontend
  only:
    - master
