# define also stages which are used in includes
default:
  image: python:alpine

stages:
  - build
  - docs
  - pack

include:
  - local: "docs/.gitlab-ci.yml"
  - local: "frontend/.gitlab-ci.yml"

pack:
  before_script:
    - echo before-script
  stage: pack
  script:
    - python3 scripts/pack.py
    - ls
    - ls frontend
    - ls backend
  artifacts:
    paths:
      - scripts
  only:
    - master
  only:
    refs:
      - master
    changes:
      - frontend/*
      - backend/*
      - docs/*
