# define also stages which are used in includes
default:
  image: python:alpine

stages:
  - build
  - docs
  - pack

include:
  - local: "docs/.gitlab-ci.yml"
  - local: "frontend/.gitlab-ci.yml"

pack:
  before_script:
    - echo before-script
  stage: pack
  script:
    - python3 scripts/pack.py
    - ls
    - ls frontend
    - ls backend
    - ls latest_package
  artifacts:
    name: "roseguarden-snapshot-$CI_COMMIT_TIMESTAMP-$CI_COMMIT_SHORT_SHA"
    paths:
      - roseguarden
  only:
    - master
  only:
    refs:
      - master

