flake8:
  stage: analysis 
  allow_failure: true  
  before_script:
    - pip install flake8
  script:
    - flake8 backend/.
  only:
    refs:
      - master
    changes:
      - backend/**/*
  except:
    changes:
      - "README.md"      