flake8:
  stage: analysis 
  allow_failure: true  
  before_script:
    - pip install flake8
  script:
    - flake8 backend/. --statistics --count $(cat files.processed)
  after_script:
    - wc -l files.processed    
  only:
    refs:
      - master
    changes:
      - backend/**/*
  except:
    changes:
      - "README.md"      

pylint:
  stage: analysis 
  allow_failure: true  
  before_script:
    - pip install pylint
  script:
    - pylint backend/*.py
  only:
    refs:
      - master
    changes:
      - backend/**/*
  except:
    changes:
      - "README.md"      

  