flake8:
  stage: analysis 
  allow_failure: true  
  before_script:
    - pip install flake8
  script:
    - flake8 backend/. --statistics  --tee --output-file=flake8_report.txt
    - python3 scripts/flake8_metrics.py flake8_report.txt
  after_script:
    - wc -l files.processed    
  only:
    refs:
      - master
    changes:
      - backend/**/*
  except:
    changes:
      - "README.md"      
  artifacts:
    reports:
      metrics: flake8_metrics.txt    

pylint:
  stage: analysis 
  allow_failure: true  
  before_script:
    - pip install pylint
  script:
    - pylint backend/*.py
  only:
    refs:
      - master
    changes:
      - backend/**/*
  except:
    changes:
      - "README.md"      

  