"""Base

Revision ID: 000001
Revises: 
Create Date: 2023-06-26 11:49:48.298284

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '000001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presence_booking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presence_booking_id'), 'presence_booking', ['id'], unique=True)
    op.create_table('presence_space',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presence_space_id'), 'presence_space', ['id'], unique=True)
    op.create_table('presence_space_slot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presence_space_slot_id'), 'presence_space_slot', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presence_space_slot_id'), table_name='presence_space_slot')
    op.drop_table('presence_space_slot')
    op.drop_index(op.f('ix_presence_space_id'), table_name='presence_space')
    op.drop_table('presence_space')
    op.drop_index(op.f('ix_presence_booking_id'), table_name='presence_booking')
    op.drop_table('presence_booking')
    # ### end Alembic commands ###
