pages:
  before_script:
    - apk add --no-cache openssl gcc musl-dev
    - pip install Cython setuptools
    - pip install mkdocs-material
    # Add your custom theme if not inside a theme_dir
    # (https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes)
    # - pip install mkdocs-material

  stage: docs 
  script:
    - mkdir -p public/
    - mkdir -p public/docs/
    - mkdir -p public/docs/api-rpc/
    - cd docs
    - mkdocs build
    - cp site/* ../public/docs/api-rpc/ -R
  artifacts:
    paths:
      - public/
  only:
    refs:
      - master
    changes:
      - docs/**/*
