site_name: roseguarden api/rpc
site_url: https://roseguarden.gitlab.io/roseguarden/docs/api-rpc

nav:
  - index.md
  - protocol.md
  - 'Actions': 
      - nodeactions.md
      - servernodeactions.md
  - 'Getting started':
      - minimal.md
  - doornodesactions.md
theme:
  name: 'material'
  custom_dir: 'theme'

markdown_extensions:
  - codehilite:
      linenums: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.progressbar
  - pymdownx.extra
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - admonition
  - footnotes
  - pymdownx.keys
  - pymdownx.arithmatex

repo_url: https://gitlab.com/roseguarden/roseguarden/-/tree/master/docs
repo_name: "gitlab:roseguarden"
edit_uri: ""